# Example .env:
# TUNNEL_TOKEN=CHANGEME

services:
  tunnel:
    build:
      context: .
    container_name: cloudflared-tunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
    network_mode: "host"
    volumes:
      - ./tunnel:/etc/cloudflared
    restart: always
